FROM ubuntu:20.04

RUN apt-get update
RUN apt install -y vim curl file libexpat1 libmagic-mgc libmagic1 libmpdec2 libpython3.8-minimal libpython3.8-stdlib libreadline8 libsqlite3-0 libssl1.1 mime-support python3.8-minimal python3-pip python3.8-venv readline-common xz-utils
RUN python3.8 -m pip install --upgrade pip
